<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InvestmentsSimulationApplications extends \Application\Model\InvestmentsSimulationApplications implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'id', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'id_simulation', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'val_application', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'date_application', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'created_at', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'updated_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'id', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'id_simulation', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'val_application', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'date_application', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'created_at', '' . "\0" . 'Application\\Model\\InvestmentsSimulationApplications' . "\0" . 'updated_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InvestmentsSimulationApplications $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSimulation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSimulation', []);

        return parent::getIdSimulation();
    }

    /**
     * {@inheritDoc}
     */
    public function getValApplication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValApplication', []);

        return parent::getValApplication();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateApplication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateApplication', []);

        return parent::getDateApplication();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSimulation($id_simulation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSimulation', [$id_simulation]);

        return parent::setIdSimulation($id_simulation);
    }

    /**
     * {@inheritDoc}
     */
    public function setValApplication($val_application)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValApplication', [$val_application]);

        return parent::setValApplication($val_application);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateApplication($date_application)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateApplication', [$date_application]);

        return parent::setDateApplication($date_application);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

}
