<?= $this->doctype() ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Teste TBB')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
        ?>


    </head>
    <body>

        <div class="container"> 
            <?= $this->render('includes/navbar.phtml') ?>
            <?= $this->content ?>

            <footer>            
                <div class="row">
                    <div class="col-md-12">
                        <p>
                            <span class="name-company">Teste TBB</span> - Alef Rogers Molar Beserra
                        </p>
                    </div>
                </div>
            </footer>
        </div>       

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/functions.js'))
                ->prependFile($this->basePath('js/jquery.mask.min.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
        ?>

    </body>
</html>
